In [1]:
import numpy as np

**Create an array of 10 zeros**

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Create an array of 10 fives**

In [3]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [6]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

**Create an array of the integers from 10 to 50**

In [4]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**Create an array of all the even integers from 10 to 50**

In [5]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Create a 3x3 matrix with values ranging from 0 to 8**

In [7]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Create a 5x5 identity matrix**

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**Use NumPy to generate an array of 25 random numbers from a standard normal distribution**

In [9]:
np.random.randn(25)

array([ 1.42005995e+00,  3.35133229e-01,  6.58860284e-01, -3.31568907e-01,
        7.52047721e-01,  1.10785362e+00, -3.00037114e-01,  1.51622039e+00,
       -7.98204064e-04,  1.87948969e-01,  9.01278433e-02,  9.71051543e-01,
       -3.88941134e-01,  6.15679240e-01,  5.84397081e-01,  1.02511481e+00,
        8.57474884e-01, -1.74901408e+00, -4.48361982e-01,  1.15955801e+00,
        7.46094961e-01, -1.10874947e+00, -8.47076906e-01, -5.73035264e-01,
       -9.90099598e-01])

**Create the following matrix**

In [3]:
### DO NOT RUN THIS CELL OR THE OUTPUT BELOW WILL DISAPPEAR

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [11]:
#Write your code in this cell to replicate the matrix above
np.linspace(.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

**In the following, subset the matrix to produce the given output.  Be careful not to run the cell that will replace the output given**

In [12]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [6]:
######DO NOT RUN THIS CELL

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [14]:
# Write your code in this cell to replicate the output above
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [7]:
######DO NOT RUN THIS CELL

20

In [8]:
# Write your code in this cell to replicate the output above

In [15]:
mat[3,4]

20

In [9]:
######DO NOT RUN THIS CELL

array([[ 2],
       [ 7],
       [12]])

In [10]:
# Write your code in this cell to replicate the output above

In [17]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [12]:
######DO NOT RUN THIS CELL

array([21, 22, 23, 24, 25])

In [ ]:
# Write your code in this cell to replicate the output above

In [18]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [13]:
######DO NOT RUN THIS CELL

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# Write your code in this cell to replicate the output above

In [20]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Summary Statistics

**Get the sum of all the values in mat**

In [22]:
mat.sum()

325

In [23]:
np.sum(mat)

325

**Get the standard deviation of the values in mat**

In [24]:
mat.std()

7.211102550927978

In [25]:
np.std(mat)

7.211102550927978

**Get the sum of each column in mat**

In [27]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [28]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])

**Add mat to its transpose (element wise)**

In [29]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
mat.T

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [31]:
mat + mat.T

array([[ 2,  8, 14, 20, 26],
       [ 8, 14, 20, 26, 32],
       [14, 20, 26, 32, 38],
       [20, 26, 32, 38, 44],
       [26, 32, 38, 44, 50]])

In [32]:
np.add(mat, mat.T)

array([[ 2,  8, 14, 20, 26],
       [ 8, 14, 20, 26, 32],
       [14, 20, 26, 32, 38],
       [20, 26, 32, 38, 44],
       [26, 32, 38, 44, 50]])